### PR TITLE
Suggestion: An alias method to output readonly array for Seq

### PR DESCRIPTION
**Pull request by hachibeeDI**
Hello,

This is a suggestion to support `ReadonlyArray<T>`.
In my opinion, ReadonlyArray is always a preferable choice than mutable one. (So they should be `toMutableArray()` and `toArray()` though, I hesitate to break backward compatibility)

Also, I think some operators are able to support that interface i.e. the result of groupBy.
I would commit for some enhancement if you feel positive against that.

Thanks!

### CODE REVIEW

**Comment by ugaya40** [comment]
@hachibeeDI 
Thank you for your prompt suggestion. Sorry it took me so long to notice.

I think you are correct.
We will consider including destructive changes. Please wait a moment.

**Comment by ugaya40** [comment]
@hachibeeDI 
I thought that `toArray()`/`toMutableArray()` would be better.

```
chunk/chunkAsync
groupBy/groupByAsync
```
needs to be modified as well.
please.

**Comment by hachibeeDI** [comment]
Sure things! I'll make some changes to my branch. one sec please...

**Comment by hachibeeDI** [comment]
Okay, now they all are marked as readonly.

**Comment by ugaya40** [comment]
@hachibeeDI 
Thank you very much!

Merged and released as [v1.4.4](https://github.com/ugaya40/leseq/releases/tag/v1.4.4)!

**Comment by ugaya40** [comment]
I made a mistake and released a patch version.
It should have been v1.5....

**Comment by hachibeeDI** [comment]
Thanks!

**Pull request merged**
